steps:
# build the container image
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud beta compute ssh --zone "asia-south1-a" $js-cicd --project "niveustraining" << EOF
    ls
   EOF
